services:

  tempo_init:
    image: &tempoImage grafana/tempo:latest
    user: root
    entrypoint: ["chown", "10001:10001", "/var/tempo"]

  tempo:
    image: *tempoImage
    container_name: tempo
    command: ["-config.file=/etc/tempo.yml"]
    volumes:
      - ./tempo.yml:/etc/tempo.yml
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - tempo_init

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: ["-config.file=/etc/loki/local-config.yaml"]
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./grafana_provisioning_prometheus.yml:/etc/grafana/provisioning/datasources/prometheus.yml
      - ./grafana_provisioning_tempo.yml:/etc/grafana/provisioning/datasources/tempo.yml
      - ./grafana_provisioning_loki.yml:/etc/grafana/provisioning/datasources/loki.yml
    ports:
      - "3000:3000"
