server:
  port : 8081
spring:
  application:
    name: serviceA
  reactor:
    context-propagation: auto
management:
  tracing:
    sampling:
      probability: 1.0 # 100%
  zipkin:
    endpoint: http://localhost:9411/api/v2/spans